version: '3.8'

services:
  takuma-db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: sampledb  
      MYSQL_USER: user  
      MYSQL_PASSWORD: password  
    ports:
      - "3306:3306"

  takuma-flask:
    build: . 
    volumes:
      - ./takuma_app:/takuma_app  
    ports: 
      - "5000:5000"
    depends_on: # takuma-flaskがtakuma-dbに依存していることを明示(起動順序を制御)
      - takuma-db
    environment:
      FLASK_APP: app.py

